/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COMMONAPI_CAN_SOMEIP_PROXY_HPP_
#define V1_COMMONAPI_CAN_SOMEIP_PROXY_HPP_

#include <v1/commonapi/CANProxyBase.hpp>
#include <v1/commonapi/CANSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Proxy.hpp>
#include <CommonAPI/SomeIP/Types.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <string>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace commonapi {

class CANSomeIPProxy
    : virtual public CANProxyBase,
      virtual public CommonAPI::SomeIP::Proxy {
public:
    CANSomeIPProxy(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection);

    virtual ~CANSomeIPProxy();

    virtual void GetHUM(CAN::HUM _hum, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_outArg, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetHUMAsync(const CAN::HUM &_hum, GetHUMAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void GetTMP(CAN::TMP _tmp, CommonAPI::CallStatus &_internalCallStatus, int8_t &_outArg, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetTMPAsync(const CAN::TMP &_tmp, GetTMPAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void GetRPM(CAN::RPM _rpm, CommonAPI::CallStatus &_internalCallStatus, uint16_t &_outArg, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetRPMAsync(const CAN::RPM &_rpm, GetRPMAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void GetSPD(CAN::SPD _spd, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_outArg, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetSPDAsync(const CAN::SPD &_spd, GetSPDAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void GetBAT(CAN::BAT _bat, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_outArg, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetBATAsync(const CAN::BAT &_bat, GetBATAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void getOwnVersion(uint16_t &_major, uint16_t &_minor) const;

    virtual std::future<void> getCompletionFuture();

private:

    std::promise<void> completed_;
};

} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_CAN_SOMEIP_PROXY_HPP_
