/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.12.v201907221223.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_CAN_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_CAN_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/commonapi/CANStub.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace commonapi {

template <typename _Stub = ::v1::commonapi::CANStub, typename... _Stubs>
class CANSomeIPStubAdapterInternal
    : public virtual CANStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> CANSomeIPStubAdapterHelper;

    ~CANSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        CANSomeIPStubAdapterHelper::deinit();
    }

    void fireHumAttributeChanged(const uint8_t& value);

    void fireTmpAttributeChanged(const int8_t& value);

    void fireRpmAttributeChanged(const uint16_t& value);

    void fireSpdAttributeChanged(const uint8_t& value);

    void fireBatAttributeChanged(const uint8_t& value);

    void deactivateManagedInstances() {
    }

    static CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::CANStub,
        CommonAPI::Version
    > getCANInterfaceVersionStubDispatcher;

    static CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::CANStub,
        uint8_t,
        CommonAPI::SomeIP::IntegerDeployment<uint8_t>
    > getHumAttributeStubDispatcher;
    static CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v1::commonapi::CANStub,
        uint8_t,
        CommonAPI::SomeIP::IntegerDeployment<uint8_t>
    > setHumAttributeStubDispatcher;
    static CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::CANStub,
        int8_t,
        CommonAPI::SomeIP::IntegerDeployment<int8_t>
    > getTmpAttributeStubDispatcher;
    static CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v1::commonapi::CANStub,
        int8_t,
        CommonAPI::SomeIP::IntegerDeployment<int8_t>
    > setTmpAttributeStubDispatcher;
    static CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::CANStub,
        uint16_t,
        CommonAPI::SomeIP::IntegerDeployment<uint16_t>
    > getRpmAttributeStubDispatcher;
    static CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v1::commonapi::CANStub,
        uint16_t,
        CommonAPI::SomeIP::IntegerDeployment<uint16_t>
    > setRpmAttributeStubDispatcher;
    static CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::CANStub,
        uint8_t,
        CommonAPI::SomeIP::IntegerDeployment<uint8_t>
    > getSpdAttributeStubDispatcher;
    static CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v1::commonapi::CANStub,
        uint8_t,
        CommonAPI::SomeIP::IntegerDeployment<uint8_t>
    > setSpdAttributeStubDispatcher;
    static CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::CANStub,
        uint8_t,
        CommonAPI::SomeIP::IntegerDeployment<uint8_t>
    > getBatAttributeStubDispatcher;
    static CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
        ::v1::commonapi::CANStub,
        uint8_t,
        CommonAPI::SomeIP::IntegerDeployment<uint8_t>
    > setBatAttributeStubDispatcher;


    CANSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        CANSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< CANStub>(_stub))
    {

                CANSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbb8) }, &getHumAttributeStubDispatcher );
                CANSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbb9) }, &setHumAttributeStubDispatcher );
                CANSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbba) }, &getTmpAttributeStubDispatcher );
                CANSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbbb) }, &setTmpAttributeStubDispatcher );
                CANSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbbc) }, &getRpmAttributeStubDispatcher );
                CANSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbbd) }, &setRpmAttributeStubDispatcher );
                CANSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbbe) }, &getSpdAttributeStubDispatcher );
                CANSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbbf) }, &setSpdAttributeStubDispatcher );
                CANSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbc0) }, &getBatAttributeStubDispatcher );
                CANSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0xbc1) }, &setBatAttributeStubDispatcher );
        
        std::shared_ptr<CommonAPI::SomeIP::ClientId> clientId = std::make_shared<CommonAPI::SomeIP::ClientId>(0xFFFF);

        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x8235)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80f2), itsEventGroups, true);
            fireHumAttributeChanged(std::dynamic_pointer_cast< ::v1::commonapi::CANStub>(_stub)->getHumAttribute(clientId));
        }

        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x8235)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80f3), itsEventGroups, true);
            fireTmpAttributeChanged(std::dynamic_pointer_cast< ::v1::commonapi::CANStub>(_stub)->getTmpAttribute(clientId));
        }

        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x8235)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80f4), itsEventGroups, true);
            fireRpmAttributeChanged(std::dynamic_pointer_cast< ::v1::commonapi::CANStub>(_stub)->getRpmAttribute(clientId));
        }

        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x8235)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80f5), itsEventGroups, true);
            fireSpdAttributeChanged(std::dynamic_pointer_cast< ::v1::commonapi::CANStub>(_stub)->getSpdAttribute(clientId));
        }

        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(CommonAPI::SomeIP::eventgroup_id_t(0x8235)));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80f6), itsEventGroups, true);
            fireBatAttributeChanged(std::dynamic_pointer_cast< ::v1::commonapi::CANStub>(_stub)->getBatAttribute(clientId));
        }

    }

private:
};

template <typename _Stub, typename... _Stubs>
CommonAPI::SomeIP::GetAttributeStubDispatcher<
    ::v1::commonapi::CANStub,
    CommonAPI::Version
    > CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::getCANInterfaceVersionStubDispatcher(&CANStub::lockInterfaceVersionAttribute, &CANStub::getInterfaceVersion, false);

template <typename _Stub, typename... _Stubs>
CommonAPI::SomeIP::GetAttributeStubDispatcher<
    ::v1::commonapi::CANStub,
    uint8_t,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::getHumAttributeStubDispatcher(
    &CANStub::lockHumAttribute,
    &CANStub::getHumAttribute, false);
template <typename _Stub, typename... _Stubs>
CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
    ::v1::commonapi::CANStub,
    uint8_t,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::setHumAttributeStubDispatcher(
    &CANStub::lockHumAttribute,
    &CANStub::getHumAttribute,
    &CANStubRemoteEvent::onRemoteSetHumAttribute,
    &CANStubRemoteEvent::onRemoteHumAttributeChanged,
    &CANStubAdapter::fireHumAttributeChanged,
    false
);

template <typename _Stub, typename... _Stubs>
CommonAPI::SomeIP::GetAttributeStubDispatcher<
    ::v1::commonapi::CANStub,
    int8_t,
    CommonAPI::SomeIP::IntegerDeployment<int8_t>
> CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::getTmpAttributeStubDispatcher(
    &CANStub::lockTmpAttribute,
    &CANStub::getTmpAttribute, false);
template <typename _Stub, typename... _Stubs>
CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
    ::v1::commonapi::CANStub,
    int8_t,
    CommonAPI::SomeIP::IntegerDeployment<int8_t>
> CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::setTmpAttributeStubDispatcher(
    &CANStub::lockTmpAttribute,
    &CANStub::getTmpAttribute,
    &CANStubRemoteEvent::onRemoteSetTmpAttribute,
    &CANStubRemoteEvent::onRemoteTmpAttributeChanged,
    &CANStubAdapter::fireTmpAttributeChanged,
    false
);

template <typename _Stub, typename... _Stubs>
CommonAPI::SomeIP::GetAttributeStubDispatcher<
    ::v1::commonapi::CANStub,
    uint16_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::getRpmAttributeStubDispatcher(
    &CANStub::lockRpmAttribute,
    &CANStub::getRpmAttribute, false);
template <typename _Stub, typename... _Stubs>
CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
    ::v1::commonapi::CANStub,
    uint16_t,
    CommonAPI::SomeIP::IntegerDeployment<uint16_t>
> CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::setRpmAttributeStubDispatcher(
    &CANStub::lockRpmAttribute,
    &CANStub::getRpmAttribute,
    &CANStubRemoteEvent::onRemoteSetRpmAttribute,
    &CANStubRemoteEvent::onRemoteRpmAttributeChanged,
    &CANStubAdapter::fireRpmAttributeChanged,
    false
);

template <typename _Stub, typename... _Stubs>
CommonAPI::SomeIP::GetAttributeStubDispatcher<
    ::v1::commonapi::CANStub,
    uint8_t,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::getSpdAttributeStubDispatcher(
    &CANStub::lockSpdAttribute,
    &CANStub::getSpdAttribute, false);
template <typename _Stub, typename... _Stubs>
CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
    ::v1::commonapi::CANStub,
    uint8_t,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::setSpdAttributeStubDispatcher(
    &CANStub::lockSpdAttribute,
    &CANStub::getSpdAttribute,
    &CANStubRemoteEvent::onRemoteSetSpdAttribute,
    &CANStubRemoteEvent::onRemoteSpdAttributeChanged,
    &CANStubAdapter::fireSpdAttributeChanged,
    false
);

template <typename _Stub, typename... _Stubs>
CommonAPI::SomeIP::GetAttributeStubDispatcher<
    ::v1::commonapi::CANStub,
    uint8_t,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::getBatAttributeStubDispatcher(
    &CANStub::lockBatAttribute,
    &CANStub::getBatAttribute, false);
template <typename _Stub, typename... _Stubs>
CommonAPI::SomeIP::SetObservableAttributeStubDispatcher<
    ::v1::commonapi::CANStub,
    uint8_t,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>
> CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::setBatAttributeStubDispatcher(
    &CANStub::lockBatAttribute,
    &CANStub::getBatAttribute,
    &CANStubRemoteEvent::onRemoteSetBatAttribute,
    &CANStubRemoteEvent::onRemoteBatAttributeChanged,
    &CANStubAdapter::fireBatAttributeChanged,
    false
);

template <typename _Stub, typename... _Stubs>
void CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireHumAttributeChanged(const uint8_t& value) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deployedValue(value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x80f2),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireTmpAttributeChanged(const int8_t& value) {
    CommonAPI::Deployable< int8_t, CommonAPI::SomeIP::IntegerDeployment<int8_t>> deployedValue(value, static_cast< CommonAPI::SomeIP::IntegerDeployment<int8_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int8_t,
                CommonAPI::SomeIP::IntegerDeployment<int8_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x80f3),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireRpmAttributeChanged(const uint16_t& value) {
    CommonAPI::Deployable< uint16_t, CommonAPI::SomeIP::IntegerDeployment<uint16_t>> deployedValue(value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint16_t,
                CommonAPI::SomeIP::IntegerDeployment<uint16_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x80f4),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireSpdAttributeChanged(const uint8_t& value) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deployedValue(value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x80f5),
        false,
        deployedValue
    );
}

template <typename _Stub, typename... _Stubs>
void CANSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireBatAttributeChanged(const uint8_t& value) {
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deployedValue(value, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
            >
    >::sendEvent(
        *this,
        CommonAPI::SomeIP::event_id_t(0x80f6),
        false,
        deployedValue
    );
}

template <typename _Stub = ::v1::commonapi::CANStub, typename... _Stubs>
class CANSomeIPStubAdapter
    : public CANSomeIPStubAdapterInternal<_Stub, _Stubs...>,
      public std::enable_shared_from_this< CANSomeIPStubAdapter<_Stub, _Stubs...>> {
public:
    CANSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          CANSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_CAN_SOMEIP_STUB_ADAPTER_HPP_
