/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COMMONAPI_HEAD_UNIT_SOMEIP_PROXY_HPP_
#define V1_COMMONAPI_HEAD_UNIT_SOMEIP_PROXY_HPP_

#include <v1/commonapi/HeadUnitProxyBase.hpp>
#include <v1/commonapi/HeadUnitSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Proxy.hpp>
#include <CommonAPI/SomeIP/Types.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <string>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace commonapi {

class HeadUnitSomeIPProxy
    : virtual public HeadUnitProxyBase,
      virtual public CommonAPI::SomeIP::Proxy {
public:
    HeadUnitSomeIPProxy(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection);

    virtual ~HeadUnitSomeIPProxy();

    virtual void GetHUM(HeadUnit::HUM _hum, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_outArg, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetHUMAsync(const HeadUnit::HUM &_hum, GetHUMAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void GetTMP(HeadUnit::TMP _tmp, CommonAPI::CallStatus &_internalCallStatus, int8_t &_outArg, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetTMPAsync(const HeadUnit::TMP &_tmp, GetTMPAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void GetRPM(HeadUnit::RPM _rpm, CommonAPI::CallStatus &_internalCallStatus, uint16_t &_outArg, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetRPMAsync(const HeadUnit::RPM &_rpm, GetRPMAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void GetSPD(HeadUnit::SPD _spd, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_outArg, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetSPDAsync(const HeadUnit::SPD &_spd, GetSPDAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void GetBAT(HeadUnit::BAT _bat, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_outArg, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetBATAsync(const HeadUnit::BAT &_bat, GetBATAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void GetPRND(HeadUnit::PRND _prnd, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_outArg, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> GetPRNDAsync(const HeadUnit::PRND &_prnd, GetPRNDAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void getOwnVersion(uint16_t &_major, uint16_t &_minor) const;

    virtual std::future<void> getCompletionFuture();

private:

    std::promise<void> completed_;
};

} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_Head_Unit_SOMEIP_PROXY_HPP_
