/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.someip 3.1.12.v201907221223.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/commonapi/CANSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace commonapi {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createCANSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< CANSomeIPProxy>(_address, _connection);
}

void initializeCANSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.CAN:v1_0:can",
        0x1234, 0x5678, 1, 0);
     CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
         CAN::getInterface(),
         &createCANSomeIPProxy);
}

INITIALIZER(registerCANSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeCANSomeIPProxy);
}

CANSomeIPProxy::CANSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection )
    {
    }



        void CANSomeIPProxy::structInMethod(const CAN::canStruct &_structParameter, CommonAPI::CallStatus &_internalCallStatus, int32_t &_output, const CommonAPI::CallInfo *_info) {
            CommonAPI::Deployable< CAN::canStruct, ::v1::commonapi::CAN_::canStructDeployment_t> deploy_structParameter(_structParameter, static_cast< ::v1::commonapi::CAN_::canStructDeployment_t* >(nullptr));
            CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_output(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
            CommonAPI::SomeIP::ProxyHelper<
                CommonAPI::SomeIP::SerializableArguments<
                    CommonAPI::Deployable<
                        CAN::canStruct,
                        ::v1::commonapi::CAN_::canStructDeployment_t
                    >
                >,
                CommonAPI::SomeIP::SerializableArguments<
                    CommonAPI::Deployable<
                        int32_t,
                        CommonAPI::SomeIP::IntegerDeployment<int32_t>
                    >
                >
            >::callMethodWithReply(
            *this,
            CommonAPI::SomeIP::method_id_t(0x7b),
            false,
            false,
    (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
    deploy_structParameter,
    _internalCallStatus,
    deploy_output);
    _output = deploy_output.getValue();
    }
    std::future<CommonAPI::CallStatus> CANSomeIPProxy::structInMethodAsync(const CAN::canStruct &_structParameter, StructInMethodAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< CAN::canStruct, ::v1::commonapi::CAN_::canStructDeployment_t> deploy_structParameter(_structParameter, static_cast< ::v1::commonapi::CAN_::canStructDeployment_t* >(nullptr));
        CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_output(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
        return CommonAPI::SomeIP::ProxyHelper<
            CommonAPI::SomeIP::SerializableArguments<
                CommonAPI::Deployable<
                    CAN::canStruct,
                    ::v1::commonapi::CAN_::canStructDeployment_t
                >
            >,
            CommonAPI::SomeIP::SerializableArguments<
                CommonAPI::Deployable<
                    int32_t,
                    CommonAPI::SomeIP::IntegerDeployment<int32_t>
                >
            >
        >::callMethodAsync(
            *this,
            CommonAPI::SomeIP::method_id_t(0x7b),
            false,
            false,
            (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
            deploy_structParameter,
            [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t> > _output) {
                if (_callback)
                    _callback(_internalCallStatus, _output.getValue());
            },
            std::make_tuple(deploy_output));
    }



    void CANSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
    }

} // namespace commonapi
} // namespace v1
