/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201907221047.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/commonapi/CANStubDefault.hpp>
#include <assert.h>

namespace v1 {
namespace commonapi {

CANStubDefault::CANStubDefault():
        remoteEventHandler_(this),
        interfaceVersion_(CAN::getInterfaceVersion()) {
}

const CommonAPI::Version& CANStubDefault::getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
    (void)_client;
    return interfaceVersion_;
}

CANStubRemoteEvent* CANStubDefault::initStubAdapter(const std::shared_ptr< CANStubAdapter> &_adapter) {
    CommonAPI::Stub<CANStubAdapter, CANStubRemoteEvent>::stubAdapter_ = _adapter;
    return &remoteEventHandler_;
}


void CANStubDefault::structInMethod(const std::shared_ptr<CommonAPI::ClientId> _client, CAN::canStruct _structParameter, structInMethodReply_t _reply) {
    (void)_client;
    (void)_structParameter;
    int32_t output = 0;
    _reply(output);
}




CANStubDefault::RemoteEventHandler::RemoteEventHandler(CANStubDefault *_defaultStub)
    : 
      defaultStub_(_defaultStub) {
}

} // namespace commonapi
} // namespace v1
