/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/commonapi/SEAMESomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createSEAMESomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< SEAMESomeIPProxy>(_address, _connection);
}

void initializeSEAMESomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.SEAME:v1_0:seame",
        0x1234, 0x5678, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "commonapi.SEAME:v1_0",
        &createSEAMESomeIPProxy);
}

INITIALIZER(registerSEAMESomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSEAMESomeIPProxy);
}

SEAMESomeIPProxy::SEAMESomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          hum_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x0), CommonAPI::SomeIP::event_id_t(0x80f2), CommonAPI::SomeIP::method_id_t(0xbb8), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)),
          tmp_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x1), CommonAPI::SomeIP::event_id_t(0x80f3), CommonAPI::SomeIP::method_id_t(0xbba), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, static_cast< CommonAPI::SomeIP::IntegerDeployment<int8_t>* >(nullptr)),
          rpm_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x2), CommonAPI::SomeIP::event_id_t(0x80f4), CommonAPI::SomeIP::method_id_t(0xbbc), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint16_t>* >(nullptr)),
          spd_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x3), CommonAPI::SomeIP::event_id_t(0x80f5), CommonAPI::SomeIP::method_id_t(0xbbe), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)),
          bat_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x4), CommonAPI::SomeIP::event_id_t(0x80f6), CommonAPI::SomeIP::method_id_t(0xbc0), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)),
          dis_(*this, CommonAPI::SomeIP::eventgroup_id_t(0x5), CommonAPI::SomeIP::event_id_t(0x80f7), CommonAPI::SomeIP::method_id_t(0xbc2), true, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr))
{
}

SEAMESomeIPProxy::~SEAMESomeIPProxy() {
    completed_.set_value();
}

SEAMESomeIPProxy::HumAttribute& SEAMESomeIPProxy::getHumAttribute() {
    return hum_;
}
SEAMESomeIPProxy::TmpAttribute& SEAMESomeIPProxy::getTmpAttribute() {
    return tmp_;
}
SEAMESomeIPProxy::RpmAttribute& SEAMESomeIPProxy::getRpmAttribute() {
    return rpm_;
}
SEAMESomeIPProxy::SpdAttribute& SEAMESomeIPProxy::getSpdAttribute() {
    return spd_;
}
SEAMESomeIPProxy::BatAttribute& SEAMESomeIPProxy::getBatAttribute() {
    return bat_;
}
SEAMESomeIPProxy::DisAttribute& SEAMESomeIPProxy::getDisAttribute() {
    return dis_;
}


void SEAMESomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> SEAMESomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace commonapi
} // namespace v1
